# Generated by Django 5.1.1 on 2025-03-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Банер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='goods_banner',
        ),
    ]
