name: Type Check with mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      working-directory: homework_02 
      run: |
        poetry install

    - name: Run mypy
      working-directory: homework_02/Basic  
      run: |
        poetry run mypy .  # Проверяем все модули в homework_02