name: Pytets

        
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd homework_03
        python -m pip install --upgrade pip
        pip install poetry
        poetry add pytest
        poetry add pytest-cov
        poerty add six
        poetry install
    - name: Run tests
      run: |
        cd homework_03
        poetry run pytest -v